name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
        - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [18.x,19.x,20.x,21.x]
    steps:
      - uses: actions/checkout@v4
      - run: cd tt-wasm && ls -lta && cd ..
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-pack
      - run: yarn install
      - run: yarn test