name: CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: Typecheck
        uses: borales/actions-yarn@v4
        with:
          cmd: typecheck
      - name: Test
        uses: borales/actions-yarn@v4
        with:
          cmd: test
